FROM centos:7
# 作者
MAINTAINER txtxw
# 设置编码
ENV LANG zh_CN.UTF-8
# 同步时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 同步时间
RUN yum -y install ntp ntpdate && \
    ntpdate cn.pool.ntp.org

# 1. 安装基本依赖
RUN yum install epel-release -y && yum makecache && yum install wget unzip epel-release nginx xz gcc gcc-devel mysql-devel python-devel automake zlib-devel openssl-devel supervisor groupinstall development libxslt-devel libxml2-devel libcurl-devel -y
#WORKDIR /var/www/

# 2. 准备python
RUN wget http://mirrors.sohu.com/python/3.6.8/Python-3.6.8.tar.xz
RUN xz -d Python-3.6.8.tar.xz && tar xvf Python-3.6.8.tar && cd Python-3.6.8 && ./configure && make && make install

# 3. 安装websdk
RUN pip3 install --upgrade pip -i https://mirrors.aliyun.com/pypi/simple/
RUN pip3 install --upgrade setuptools -i https://mirrors.aliyun.com/pypi/simple/
RUN pip3 install uwsgi -i https://mirrors.aliyun.com/pypi/simple/
#RUN pip3 install -U git+https://github.com/ss1917/ops_sdk.git


# 4. 复制代码
RUN mkdir -p /var/www/
ADD . /var/www/

# 5. 安装pip依赖 （生成不全，待解决）
RUN pip3 install -r /var/www/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

# 6. 日志
VOLUME /var/log/

# 7. 准备文件
COPY nginx.conf /etc/nginx/nginx.conf


EXPOSE 80

CMD ["/bin/bash","start.sh"]