# Generated by Django 2.2.12 on 2020-04-24 15:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('desc', models.CharField(max_length=300, verbose_name='课程简介')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=6, verbose_name='难度')),
                ('learn_time', models.IntegerField(default=0, verbose_name='学习时长')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('category', models.CharField(default='后端开发', max_length=20, verbose_name='学习类别')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击人数')),
                ('youneed_know', models.CharField(default='', max_length=200, verbose_name='课程须知')),
                ('tearcher_tell', models.CharField(default='', max_length=200, verbose_name='老师告诉你')),
                ('detail', models.CharField(default='', max_length=300, verbose_name='课程详情')),
                ('image', models.ImageField(upload_to='media/courses/%Y/%m', verbose_name='课程封面')),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='课程费用')),
                ('course_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='课程机构')),
                ('tearcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Teachers', verbose_name='课程老师')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=50, verbose_name='章节名称')),
                ('learn_time', models.IntegerField(default=0, verbose_name='学习时长')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Courses')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100, verbose_name='视频名称')),
                ('learn_time', models.IntegerField(default=0, verbose_name='学习时长')),
                ('url', models.CharField(max_length=200, verbose_name='视频地址')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Lessons')),
            ],
            options={
                'verbose_name': '学习视频',
                'verbose_name_plural': '学习视频',
            },
        ),
        migrations.CreateModel(
            name='CourseSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('file', models.FileField(upload_to='media/courses/%Y/%m', verbose_name='下载地址')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Courses')),
            ],
            options={
                'verbose_name': '课程资源',
                'verbose_name_plural': '课程资源',
            },
        ),
    ]
